.Dd May 3, 2020
.Os zmk @VERSION@
.Dt zmk.Buildable 5 PRM
.Sh NAME
.Nm Buildable
.Nd template for files that can built and cleaned
.Sh SYNOPSIS
.Bd -literal
include z.mk

$(eval $(call ZMK.Expand,Buildable,NAME))
.Ed
.Sh DESCRIPTION
The template
.Nm Buildable
once
.Em expanded
with a target
.Nm NAME
makes
.Nm all
depend on
.Nm NAME ,
and makes
.Nm clean
remove
.Nm NAME .
It can be used to avoid duplicating the same two rules across many
buildable entities. It is used internally by zmk in other templates.
.Pp
Actual rules for building
.Nm NAME
need to be provided manually.
.Sh TARGETS
This module provides the following targets.
.Ss all
The
.Nm all
target depends on
.Nm NAME .
.Ss clean
The
.Nm clean
target removes
.Nm NAME .
.Sh VARIABLES
This module does not provide any variables.
.Sh HISTORY
The
.Nm
template first appeared in zmk 0.3
.Sh AUTHORS
.An "Zygmunt Krynicki" Aq Mt me@zygoon.pl
