.Dd May 3, 2020
.Os zmk @VERSION@
.Dt zmk.Template.program 3 PRM
.Sh NAME
.Nm Template.program
.Nd make template for compiling C/C++ programs
.Sh SYNOPSIS
.Bd -literal
include z.mk

NAME.sources = hello.c
$(eval $(call spawn,Template.program,NAME))
.Ed
.Sh DESCRIPTION
The template
.Nm Template.program
once
.Em spawned
with a
.Em program name
to creates rules for compiling, cleaning, installing and removing a single program written in C, C++ or Objective C.
.Pp
Source files are compiled to object files prefixed with
.Em NAME- ,
so that individual source files can be part of many different programs,
using distinct preprocessor, compiler and linker options.
.Pp
If cross-compiling for
.Em Windows
or
.Em DOS ,
the
.Em $(exe)
variable expands to
.Em .exe
.Sh TARGETS
.Ss NAME$(exe)
This target represents the program executable.
.Pp
If using
.Em gcc
or
.Em clang
the resulting binary is compiled as a
.Em position-independent executable ,
by setting
.Em CFLAGS += -fPIE .
.Ss all
The
.Nm all
target depends on
.Em NAME$(exe)
.Ss clean
The
.Nm clean
target removes
.Em NAME$(exe)
and
.Em NAME-*.o
.Ss install
The
.Nm install
target copies
.Em NAME$(exe) ,
with mode
.Em $(NAME.install_mode) ,
to
.Em $(NAME.install_dir) ,
creating it if necessary.
.Ss uninstall
The
.Nm uninstall
target removes
.Em NAME$(exe)
as installed by the
.Em install
target.
.Sh VARIABLES
.Ss NAME.sources
List of source files to compile.
.Pp
There is no default value. This variable must be set before
.Em spawning
the template.
.Ss NAME.objects
List of object files to link.
.Pp
The default value is all the elements of
.Em NAME.sources
with the added prefix
.Em NAME-
and with the extension replaced by
.Em .o .
.Ss NAME.install_dir
The directory
.Em NAME$(exe)
is installed to.
.Pp
The default value is
.Em $(bindir)
but
.Em $(sbindir)
or
.Em $(libexecdir)
are commonly used as well. The special value
.Em noinst
disables the rules related to installation and uninstallation.
.Ss NAME.install_mode
The UNIX mode
.Em NAME$(exe)
is installed with.
.Pp
The default value is
.Em 0755 .
.Ss DESTDIR
Path added to all installation targets.
This variable is normally set externally, to install a compiled program
into a staging area during construction of a compiled binary package.
.Ss CFLAGS, CXXFLAGS, OBJCFLAGS
Options for the C, C++ and the Objective C compiler, respectively.
.Ss CPPFLAGS
Options for the preprocessor.
.Sh IMPLEMENTATION NOTES
.Nm
uses
.Nm Template.data
to install the compiled program.
.Sh EXAMPLES
With the following
.Em true_false.c
file:
.Bd -literal -offset indent-two
#include <stdlib.h>

int main(void) {
	return EXIT_CODE;
}
.Ed
.Pp
The following
.Em Makefile
builds the classic programs
.Em true
and
.Em false .
.Bd -literal -offset indent-two
include z.mk
NAME = true_false

true.sources = true_false.c
$(eval $(call spawn,Template.program,true))
true$(exe): CPPFLAGS += -DEXIT_CODE=EXIT_SUCCESS

false.sources = true_false.c
$(eval $(call spawn,Template.program,false))
false$(exe): CPPFLAGS += -DEXIT_CODE=EXIT_FAILURE
.Ed
.Sh HISTORY
The
.Nm
module first appeared in zmk 0.1
.Sh AUTHORS
.An "Zygmunt Krynicki" Aq Mt me@zygoon.pl
