include z.mk

$(eval $(call ZMK.Expand,ManPage,foo.1))
$(eval $(call ZMK.Expand,ManPage,foo.2))
$(eval $(call ZMK.Expand,ManPage,foo.3))
$(eval $(call ZMK.Expand,ManPage,foo.4))
$(eval $(call ZMK.Expand,ManPage,foo.5))
$(eval $(call ZMK.Expand,ManPage,foo.6))
$(eval $(call ZMK.Expand,ManPage,foo.7))
$(eval $(call ZMK.Expand,ManPage,foo.8))
$(eval $(call ZMK.Expand,ManPage,foo.9))
