# SPDX-FileCopyrightText: 2019-2024 Zygmunt Krynicki
# SPDX-License-Identifier: LGPL-3.0-only
#
# This file is part of zmk.
#
# Zmk is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3 as
# published by the Free Software Foundation.
#
# Zmk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Zmk.  If not, see <https://www.gnu.org/licenses/>.

include z.mk

$(eval $(call ZMK.Expand,ManPage,foo.1))
$(eval $(call ZMK.Expand,ManPage,foo.2))
$(eval $(call ZMK.Expand,ManPage,foo.3))
$(eval $(call ZMK.Expand,ManPage,foo.4))
$(eval $(call ZMK.Expand,ManPage,foo.5))
$(eval $(call ZMK.Expand,ManPage,foo.6))
$(eval $(call ZMK.Expand,ManPage,foo.7))
$(eval $(call ZMK.Expand,ManPage,foo.8))
$(eval $(call ZMK.Expand,ManPage,foo.9))

$(eval $(call ZMK.Expand,ManPage,man/bar.1))
$(eval $(call ZMK.Expand,ManPage,man/bar.2))
$(eval $(call ZMK.Expand,ManPage,man/bar.3))
$(eval $(call ZMK.Expand,ManPage,man/bar.4))
$(eval $(call ZMK.Expand,ManPage,man/bar.5))
$(eval $(call ZMK.Expand,ManPage,man/bar.6))
$(eval $(call ZMK.Expand,ManPage,man/bar.7))
$(eval $(call ZMK.Expand,ManPage,man/bar.8))
$(eval $(call ZMK.Expand,ManPage,man/bar.9))
